### ISSUE TITLE
transcoder simplexml_load_file() undefined function

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-websanlexicon#7]
Error message
```
[Sun Oct 20 11:25:02.902615 2019] [php7:error] [pid 5635] [client 127.0.0.1:38496] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/cologne/mw/web/utilities/transcoder.php:41\nStack trace:\n#0 /var/www/html/cologne/mw/web/utilities/transcoder.php(265): transcoder_fsm('hk', 'slp1')\n#1 /var/www/html/cologne/mw/web/webtc/parm.php(58): transcoder_processString('', 'hk', 'slp1')\n#2 /var/www/html/cologne/mw/web/webtc2/queryparm.php(36): Parm->__construct('mw')\n#3 /var/www/html/cologne/mw/web/webtc2/query.php(15): Queryparm->__construct('mw')\n#4 {main}\n  thrown in /var/www/html/cologne/mw/web/utilities/transcoder.php on line 41, referer: http://localhost/cologne/mw/web/webtc2/index.php
```

**Comment by drdhaval2785** [comment]
`sudo apt install php-xml` and `sudo service apache2 restart` seems to correct this error.
In official ubuntu repository the xml part of php seems to be supplied by `php-xml` package.
